# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_auto_20181230_1410'),
        ('financeur', '0002_auto_20181230_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='financement',
            name='projet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projet.Projet'),
        ),
    ]
