# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projet', '0001_initial'),
        ('the_project_factory_default', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Critere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karma', models.IntegerField(default=0)),
                ('Personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='the_project_factory_default.Personne')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(default=0)),
                ('Evaluateur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='evaluateur.Evaluateur')),
                ('Projet', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projet.Projet')),
                ('Type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projet.Type')),
            ],
        ),
    ]
