# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('the_project_factory_default', '0001_initial'),
        ('evaluateur', '0001_initial'),
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='Projet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projet.Projet'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='Type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projet.Type'),
        ),
        migrations.AddField(
            model_name='evaluateur',
            name='Personne',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='the_project_factory_default.Personne'),
        ),
    ]
