# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 10:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_project_factory_default', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
