# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_project_factory_default', '0002_auto_20181207_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
