# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(max_length=300)),
                ('mail', models.EmailField(default=None, max_length=254)),
            ],
        ),
    ]
