# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('the_project_factory_default', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoProjet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_projet/')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.Type'),
        ),
        migrations.AddField(
            model_name='projet',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_project_factory_default.Personne'),
        ),
        migrations.AddField(
            model_name='photoprojet',
            name='Projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.Projet'),
        ),
    ]
