# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_auto_20181230_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireProjet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=300)),
                ('mail', models.EmailField(default=None, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_projet/'),
        ),
        migrations.AddField(
            model_name='commentaireprojet',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.Projet'),
        ),
    ]
