# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_auto_20190120_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaireprojet',
            name='texte',
            field=models.TextField(max_length=300),
        ),
    ]
