# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('the_project_factory_default', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='the_project_factory_default.Personne')),
            ],
        ),
    ]
